### PR TITLE
Fix timeout test case in MariaDB builds

### PR DESCRIPTION
**Pull request by zuiderkwast**
Accept SLEEP to return error 1317 "70100" ("Query execution was ...") when interrupted, apparently what we get on the failing MariaDB builds on other PRs.

### CODE REVIEW

**Review by Maria-12648430 — APPROVED** [review]
A review for a MariaDB-related fix... guess I had that coming 😅

Anyway, looks good to me, approved :)

**Review by juhlig — APPROVED** [review]
Looks good, the Travis tests pass again now, too.

**Comment by juhlig** [comment]
@Maria-12648430 I _told_ you something like this would happen one day ;)

**Comment by zuiderkwast** [comment]
Thanks. Yes Maria, you're our de-facto MariaDB responsible from now on. :)

**Comment by Maria-12648430** [comment]
> Thanks. Yes Maria, you're our de-facto MariaDB responsible from now on. :)

Oh dear... 😬

**Comment by Maria-12648430** [comment]
> @Maria-12648430 I _told_ you something like this would happen one day ;)

You should have told my _parents_ ^^;;;;;

**Pull request merged**
