### PR TITLE
Handle socket closed error from tcp conn (#196)

### LINKED ISSUE #196: mysql_protocol:recv_packet(...) returns {error, closed} that unhandled in mysql_protocol:fetch_response.
vs8JzNZcXX

### PR DESCRIPTION
**Pull request by krishnakumar4a4**
Fixes #196 and addressed comments as part of #173 as well

### CODE REVIEW

**Review by zuiderkwast — COMMENTED** [review]
Nice!

Doesn't it affect the return type of execute/7 too?

**Comment by krishnakumar4a4** [comment]
Yes, it does. Updated it.

**Comment by zuiderkwast** [comment]
Good. And where this is handled in mysql_conn, in execute_stmt I guess..?

**Review by zuiderkwast — APPROVED** [review]
Thanks, it looks good now. I will merge it soon. I'm just thinking about a way to test it, if it's possible to do it in a simple way. Do you know some way we can test it?

**Pull request merged**
