### PR TITLE
Fix issue #33: mysql_socket to detect TCP Closed by Server

### PR DESCRIPTION
**Pull request by emqplus**
First of all, thanks @zuiderkwast for the awesome Erlang MySQL driver. I am the author of http://github.com/emqtt/. We received lots of issue reports after we use mysql-otp as MySQL driver in 0.17.x release:

https://github.com/emqtt/emqttd/issues/586

https://github.com/emqtt/emqttd/issues/523

https://github.com/emqtt/emqttd_plugin_mysql/issues/15

The root cause is mysql-otp use gen_tcp:recv to receive data passively. The client cannot receive tcp_closed event when MySQL server tries to shutdown idle clients.

We refactored the socket layer, which use '{active, once}' to receive tcp data like emqttc did:

Socket

### CODE REVIEW

**Comment by emqplus** [comment]
@newsdy,  @alexshavelev, please help to verify the PR

**Comment by RaoH** [comment]
Sorry of the absence, usual excuse of work is taking a lot of time!

I will test this MR locally and get back to you! But it looks good from my viewpoint =)

**Comment by zuiderkwast** [comment]
Thanks for your effort @emqplus! It is a lot of changes. Refactoring makes it hard to see what has actually been changed and what has just been moved to other files. Apart from receiving messages in a receive loop using {active, once}, you have also implemented SSL and some other things that I don't know why they are done. When all comes in one PR it makes it hard to merge while keeping up the minimalist and clear approach of this project. Also there are some things that I don't understand such as why a separate controlling process is assigned and why the tcp_closed and other messages are received using a recursive receive loop (and why that process is hibernating) instead of in handle_info in the gen_server. To me, this makes the code harder to understand.

Due to the large changes I find it easier to accept a simple PR such as #41. Then I would be interested to see a separate PR for SSL.

**Comment by emqplus** [comment]
Hi @zuiderkwast, 

1. A separate process which is responsible to receive and parse raw TCP data into protocol packets seems a design pattern for erlang socket layer. The pattern is wildly used and proved by some projects:

RabbitMQ: https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_reader.erl

ejabberd: https://github.com/processone/exmpp/blob/master/src/network/exmpp_socket.erl

emqttc: https://github.com/emqtt/emqttc

2. If we use the main mysql client process to receive TCP data, we have to call 'inet:setopts/2' to activate/deactivate the socket in many places.

3. The receiver process will hibernates to GC the refc binaries allocated for TCP data.

I'd like to remove the SSL supports from this PR and submit a new one. I hope we could invite more contributors to discuss and improve the socket layer for the issue #33 makes this driver cannot be used wildly by erlang communities.

Thanks for your awesome work. mysql-otp is the best Erlang MySQL driver, I think:)

**Comment by zuiderkwast** [comment]
Thanks for your clarifications. There are only 14 places we have to call `inet:setopts/2` (twice for each of these places). As you can see in #41 there is not very much code required to do this. Considering we are only working with one connection I think the extra receiver process which needs to be garbage collected is adding complexity and I cannot see how this would be improving performance. Feel free to explain to me if I'm wrong.

**Comment by emqplus** [comment]
@zuiderkwast, If the issue #31 could be fixed by PR #41, this PR is not necessary to merge. Usually the  design pattern is for asynchronous client driver, in which case the main client process will not block to wait for a response. I will upgrade the driver we used to 1.2.0 first, thanks.

**Comment by zuiderkwast** [comment]
OK, great. Yes, I agree, for an asynchronous driver the socket layer would make more sense. I'm closing this in favour of #41 then.

**Pull request closed without merging**
